CREATE TABLE IF NOT EXISTS "mpa" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(5),
  CONSTRAINT uq_mpa_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS "film" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description varchar(200),
  release_date date,
  duration float4,
  mpa_id int8 REFERENCES "mpa" (id),
  CONSTRAINT film_check CHECK (name <> ''
    AND (release_date < NOW() AND release_date > '1895-12-28'::date)
    AND duration > 0)
);

CREATE TABLE IF NOT EXISTS "user" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar,
  login varchar,
  name varchar,
  birthday date,
  CONSTRAINT user_check CHECK (login <> ''
    AND birthday < NOW())
);

CREATE TABLE IF NOT EXISTS "friendship" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int8 REFERENCES "user" (id),
  friend_id int8 REFERENCES "user" (id),
  is_confirmed boolean,
  CONSTRAINT uq_user_friend_ids UNIQUE (user_id, friend_id),
  CONSTRAINT uq_friend_user_ids UNIQUE (friend_id, user_id)
);

CREATE TABLE IF NOT EXISTS "likes" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int8 REFERENCES "user" (id),
  film_id int8 REFERENCES "film" (id),
  CONSTRAINT uq_user_film_ids UNIQUE (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS "genre" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  CONSTRAINT uq_genre_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS "film_genres" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id int8 REFERENCES "film" (id),
  genre_id int8 REFERENCES "genre" (id),
  CONSTRAINT uq_film_genre_ids UNIQUE (film_id, genre_id)
);
