CREATE TABLE IF NOT EXISTS "mpa" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(5)
);

CREATE TABLE IF NOT EXISTS "film" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description varchar(200),
  release_date date,
  duration float4,
  mpa_id int8 REFERENCES "mpa" (id)
);

CREATE TABLE IF NOT EXISTS "user" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar,
  login varchar,
  name varchar,
  birthday date
);

CREATE TABLE IF NOT EXISTS "friendship" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int8 REFERENCES "user" (id),
  friend_id int8 REFERENCES "user" (id),
  is_confirmed boolean,
  CONSTRAINT uq_user_friend_ids UNIQUE (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS "likes" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int8 REFERENCES "user" (id),
  film_id int8 REFERENCES "film" (id),
  CONSTRAINT uq_user_film_ids UNIQUE (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS "genre" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar
);

CREATE TABLE IF NOT EXISTS "film_genres" (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id int8 REFERENCES "film" (id),
  genre_id int8 REFERENCES "genre" (id),
  CONSTRAINT uq_film_genre_ids UNIQUE (film_id, genre_id)
);
